#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libssh2
Version  : 1.10.0
Release  : 308
URL      : file:///aot/build/clearlinux/packages/libssh2/libssh2-v1.10.0.tar.gz
Source0  : file:///aot/build/clearlinux/packages/libssh2/libssh2-v1.10.0.tar.gz
Summary  : Library for SSH-based communication
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libssh2-lib = %{version}-%{release}
Requires: libssh2-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : pkg-config
BuildRequires : pkgconfig(openssl)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libssh2 - SSH2 library
======================
libssh2 is a library implementing the SSH2 protocol, available under
the revised BSD license.

%package dev
Summary: dev components for the libssh2 package.
Group: Development
Requires: libssh2-lib = %{version}-%{release}
Provides: libssh2-devel = %{version}-%{release}
Requires: libssh2 = %{version}-%{release}

%description dev
dev components for the libssh2 package.


%package doc
Summary: doc components for the libssh2 package.
Group: Documentation
Requires: libssh2-man = %{version}-%{release}

%description doc
doc components for the libssh2 package.


%package lib
Summary: lib components for the libssh2 package.
Group: Libraries

%description lib
lib components for the libssh2 package.


%package man
Summary: man components for the libssh2 package.
Group: Default

%description man
man components for the libssh2 package.


%package staticdev
Summary: staticdev components for the libssh2 package.
Group: Default
Requires: libssh2-dev = %{version}-%{release}

%description staticdev
staticdev components for the libssh2 package.


%prep
%setup -q -n libssh2
cd %{_builddir}/libssh2

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631658755
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
## -pthread -lpthread
## -Wl,-Bsymbolic-functions
export CXXFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export CFFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags1 end
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_FLAGS_RELEASE:STRING="-Ofast -DNDEBUG" \
-DCMAKE_CXX_FLAGS_RELEASE:STRING="-Ofast -DNDEBUG" \
-DENABLE_ZLIB_COMPRESSION:BOOL=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF
## make_prepend64 content
sd "\-lz" "/usr/lib64/libz.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
sd "\-lpcre2-8" "/usr/lib64/libpcre2-8.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
sd "\-lssl" "/usr/lib64/libssl.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
sd "\-lcrypto" "/usr/lib64/libcrypto.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
## make_prepend64 end
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd
mkdir -p clr-build-special
pushd clr-build-special
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
## -pthread -lpthread
## -Wl,-Bsymbolic-functions
export CXXFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export CFFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g3 -ggdb -Ofast -fopt-info-vec --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags1 end
%cmake .. -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_FLAGS_RELEASE:STRING="-Ofast -DNDEBUG" \
-DCMAKE_CXX_FLAGS_RELEASE:STRING="-Ofast -DNDEBUG" \
-DENABLE_ZLIB_COMPRESSION:BOOL=ON \
-DBUILD_SHARED_LIBS:BOOL=ON
## make_prepend64 content
sd "\-lz" "/usr/lib64/libz.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
sd "\-lpcre2-8" "/usr/lib64/libpcre2-8.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
sd "\-lssl" "/usr/lib64/libssl.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
sd "\-lcrypto" "/usr/lib64/libcrypto.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$) $(fd -uu --follow link\.txt$)
## make_prepend64 end
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1631658755
rm -rf %{buildroot}
pushd clr-build-special
%make_install_special  || :
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libssh2.h
/usr/include/libssh2_publickey.h
/usr/include/libssh2_sftp.h
/usr/lib64/cmake/libssh2/Libssh2Config-release.cmake
/usr/lib64/cmake/libssh2/Libssh2Config.cmake
/usr/lib64/cmake/libssh2/Libssh2ConfigVersion.cmake
/usr/lib64/libssh2.so
/usr/lib64/pkgconfig/libssh2.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libssh2/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libssh2.so.1
/usr/lib64/libssh2.so.1.0.1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man3/libssh2_agent_connect.3
/usr/share/man/man3/libssh2_agent_disconnect.3
/usr/share/man/man3/libssh2_agent_free.3
/usr/share/man/man3/libssh2_agent_get_identity.3
/usr/share/man/man3/libssh2_agent_get_identity_path.3
/usr/share/man/man3/libssh2_agent_init.3
/usr/share/man/man3/libssh2_agent_list_identities.3
/usr/share/man/man3/libssh2_agent_set_identity_path.3
/usr/share/man/man3/libssh2_agent_userauth.3
/usr/share/man/man3/libssh2_banner_set.3
/usr/share/man/man3/libssh2_base64_decode.3
/usr/share/man/man3/libssh2_channel_close.3
/usr/share/man/man3/libssh2_channel_direct_tcpip.3
/usr/share/man/man3/libssh2_channel_direct_tcpip_ex.3
/usr/share/man/man3/libssh2_channel_eof.3
/usr/share/man/man3/libssh2_channel_exec.3
/usr/share/man/man3/libssh2_channel_flush.3
/usr/share/man/man3/libssh2_channel_flush_ex.3
/usr/share/man/man3/libssh2_channel_flush_stderr.3
/usr/share/man/man3/libssh2_channel_forward_accept.3
/usr/share/man/man3/libssh2_channel_forward_cancel.3
/usr/share/man/man3/libssh2_channel_forward_listen.3
/usr/share/man/man3/libssh2_channel_forward_listen_ex.3
/usr/share/man/man3/libssh2_channel_free.3
/usr/share/man/man3/libssh2_channel_get_exit_signal.3
/usr/share/man/man3/libssh2_channel_get_exit_status.3
/usr/share/man/man3/libssh2_channel_handle_extended_data.3
/usr/share/man/man3/libssh2_channel_handle_extended_data2.3
/usr/share/man/man3/libssh2_channel_ignore_extended_data.3
/usr/share/man/man3/libssh2_channel_open_ex.3
/usr/share/man/man3/libssh2_channel_open_session.3
/usr/share/man/man3/libssh2_channel_process_startup.3
/usr/share/man/man3/libssh2_channel_read.3
/usr/share/man/man3/libssh2_channel_read_ex.3
/usr/share/man/man3/libssh2_channel_read_stderr.3
/usr/share/man/man3/libssh2_channel_receive_window_adjust.3
/usr/share/man/man3/libssh2_channel_receive_window_adjust2.3
/usr/share/man/man3/libssh2_channel_request_pty.3
/usr/share/man/man3/libssh2_channel_request_pty_ex.3
/usr/share/man/man3/libssh2_channel_request_pty_size.3
/usr/share/man/man3/libssh2_channel_request_pty_size_ex.3
/usr/share/man/man3/libssh2_channel_send_eof.3
/usr/share/man/man3/libssh2_channel_set_blocking.3
/usr/share/man/man3/libssh2_channel_setenv.3
/usr/share/man/man3/libssh2_channel_setenv_ex.3
/usr/share/man/man3/libssh2_channel_shell.3
/usr/share/man/man3/libssh2_channel_subsystem.3
/usr/share/man/man3/libssh2_channel_wait_closed.3
/usr/share/man/man3/libssh2_channel_wait_eof.3
/usr/share/man/man3/libssh2_channel_window_read.3
/usr/share/man/man3/libssh2_channel_window_read_ex.3
/usr/share/man/man3/libssh2_channel_window_write.3
/usr/share/man/man3/libssh2_channel_window_write_ex.3
/usr/share/man/man3/libssh2_channel_write.3
/usr/share/man/man3/libssh2_channel_write_ex.3
/usr/share/man/man3/libssh2_channel_write_stderr.3
/usr/share/man/man3/libssh2_channel_x11_req.3
/usr/share/man/man3/libssh2_channel_x11_req_ex.3
/usr/share/man/man3/libssh2_exit.3
/usr/share/man/man3/libssh2_free.3
/usr/share/man/man3/libssh2_hostkey_hash.3
/usr/share/man/man3/libssh2_init.3
/usr/share/man/man3/libssh2_keepalive_config.3
/usr/share/man/man3/libssh2_keepalive_send.3
/usr/share/man/man3/libssh2_knownhost_add.3
/usr/share/man/man3/libssh2_knownhost_addc.3
/usr/share/man/man3/libssh2_knownhost_check.3
/usr/share/man/man3/libssh2_knownhost_checkp.3
/usr/share/man/man3/libssh2_knownhost_del.3
/usr/share/man/man3/libssh2_knownhost_free.3
/usr/share/man/man3/libssh2_knownhost_get.3
/usr/share/man/man3/libssh2_knownhost_init.3
/usr/share/man/man3/libssh2_knownhost_readfile.3
/usr/share/man/man3/libssh2_knownhost_readline.3
/usr/share/man/man3/libssh2_knownhost_writefile.3
/usr/share/man/man3/libssh2_knownhost_writeline.3
/usr/share/man/man3/libssh2_poll.3
/usr/share/man/man3/libssh2_poll_channel_read.3
/usr/share/man/man3/libssh2_publickey_add.3
/usr/share/man/man3/libssh2_publickey_add_ex.3
/usr/share/man/man3/libssh2_publickey_init.3
/usr/share/man/man3/libssh2_publickey_list_fetch.3
/usr/share/man/man3/libssh2_publickey_list_free.3
/usr/share/man/man3/libssh2_publickey_remove.3
/usr/share/man/man3/libssh2_publickey_remove_ex.3
/usr/share/man/man3/libssh2_publickey_shutdown.3
/usr/share/man/man3/libssh2_scp_recv.3
/usr/share/man/man3/libssh2_scp_recv2.3
/usr/share/man/man3/libssh2_scp_send.3
/usr/share/man/man3/libssh2_scp_send64.3
/usr/share/man/man3/libssh2_scp_send_ex.3
/usr/share/man/man3/libssh2_session_abstract.3
/usr/share/man/man3/libssh2_session_banner_get.3
/usr/share/man/man3/libssh2_session_banner_set.3
/usr/share/man/man3/libssh2_session_block_directions.3
/usr/share/man/man3/libssh2_session_callback_set.3
/usr/share/man/man3/libssh2_session_disconnect.3
/usr/share/man/man3/libssh2_session_disconnect_ex.3
/usr/share/man/man3/libssh2_session_flag.3
/usr/share/man/man3/libssh2_session_free.3
/usr/share/man/man3/libssh2_session_get_blocking.3
/usr/share/man/man3/libssh2_session_get_timeout.3
/usr/share/man/man3/libssh2_session_handshake.3
/usr/share/man/man3/libssh2_session_hostkey.3
/usr/share/man/man3/libssh2_session_init.3
/usr/share/man/man3/libssh2_session_init_ex.3
/usr/share/man/man3/libssh2_session_last_errno.3
/usr/share/man/man3/libssh2_session_last_error.3
/usr/share/man/man3/libssh2_session_method_pref.3
/usr/share/man/man3/libssh2_session_methods.3
/usr/share/man/man3/libssh2_session_set_blocking.3
/usr/share/man/man3/libssh2_session_set_last_error.3
/usr/share/man/man3/libssh2_session_set_timeout.3
/usr/share/man/man3/libssh2_session_startup.3
/usr/share/man/man3/libssh2_session_supported_algs.3
/usr/share/man/man3/libssh2_sftp_close.3
/usr/share/man/man3/libssh2_sftp_close_handle.3
/usr/share/man/man3/libssh2_sftp_closedir.3
/usr/share/man/man3/libssh2_sftp_fsetstat.3
/usr/share/man/man3/libssh2_sftp_fstat.3
/usr/share/man/man3/libssh2_sftp_fstat_ex.3
/usr/share/man/man3/libssh2_sftp_fstatvfs.3
/usr/share/man/man3/libssh2_sftp_fsync.3
/usr/share/man/man3/libssh2_sftp_get_channel.3
/usr/share/man/man3/libssh2_sftp_init.3
/usr/share/man/man3/libssh2_sftp_last_error.3
/usr/share/man/man3/libssh2_sftp_lstat.3
/usr/share/man/man3/libssh2_sftp_mkdir.3
/usr/share/man/man3/libssh2_sftp_mkdir_ex.3
/usr/share/man/man3/libssh2_sftp_open.3
/usr/share/man/man3/libssh2_sftp_open_ex.3
/usr/share/man/man3/libssh2_sftp_opendir.3
/usr/share/man/man3/libssh2_sftp_read.3
/usr/share/man/man3/libssh2_sftp_readdir.3
/usr/share/man/man3/libssh2_sftp_readdir_ex.3
/usr/share/man/man3/libssh2_sftp_readlink.3
/usr/share/man/man3/libssh2_sftp_realpath.3
/usr/share/man/man3/libssh2_sftp_rename.3
/usr/share/man/man3/libssh2_sftp_rename_ex.3
/usr/share/man/man3/libssh2_sftp_rewind.3
/usr/share/man/man3/libssh2_sftp_rmdir.3
/usr/share/man/man3/libssh2_sftp_rmdir_ex.3
/usr/share/man/man3/libssh2_sftp_seek.3
/usr/share/man/man3/libssh2_sftp_seek64.3
/usr/share/man/man3/libssh2_sftp_setstat.3
/usr/share/man/man3/libssh2_sftp_shutdown.3
/usr/share/man/man3/libssh2_sftp_stat.3
/usr/share/man/man3/libssh2_sftp_stat_ex.3
/usr/share/man/man3/libssh2_sftp_statvfs.3
/usr/share/man/man3/libssh2_sftp_symlink.3
/usr/share/man/man3/libssh2_sftp_symlink_ex.3
/usr/share/man/man3/libssh2_sftp_tell.3
/usr/share/man/man3/libssh2_sftp_tell64.3
/usr/share/man/man3/libssh2_sftp_unlink.3
/usr/share/man/man3/libssh2_sftp_unlink_ex.3
/usr/share/man/man3/libssh2_sftp_write.3
/usr/share/man/man3/libssh2_trace.3
/usr/share/man/man3/libssh2_trace_sethandler.3
/usr/share/man/man3/libssh2_userauth_authenticated.3
/usr/share/man/man3/libssh2_userauth_hostbased_fromfile.3
/usr/share/man/man3/libssh2_userauth_hostbased_fromfile_ex.3
/usr/share/man/man3/libssh2_userauth_keyboard_interactive.3
/usr/share/man/man3/libssh2_userauth_keyboard_interactive_ex.3
/usr/share/man/man3/libssh2_userauth_list.3
/usr/share/man/man3/libssh2_userauth_password.3
/usr/share/man/man3/libssh2_userauth_password_ex.3
/usr/share/man/man3/libssh2_userauth_publickey.3
/usr/share/man/man3/libssh2_userauth_publickey_fromfile.3
/usr/share/man/man3/libssh2_userauth_publickey_fromfile_ex.3
/usr/share/man/man3/libssh2_userauth_publickey_frommemory.3
/usr/share/man/man3/libssh2_version.3

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libssh2.a
